### ISSUE TITLE
If unit is not visible, center on unit when waiting for its turn

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#147]
Moving screen away from unit makes the unit invisible even on the next turn.

**Comment by SWY1985** [comment]
The issue appears to have been solved, can anyone confirm that?

**Comment by AlexFolland** [comment]
I don't fully understand this report.  What are the steps to reproduce?

**Comment by SWY1985** [comment]
There used to be an issue with units disappearing, but since this issue was reported 6 months ago and many related issues have been solved, I don't think we can reproduce this anymore.

**Comment by AlexFolland** [comment]
I have seen Carrier units disappear recently, becoming unable to be clicked on to be activated, but still existing and given control on subsequent turns.  If it is encountered again, a clearer bug report can be opened.  I think this one can be closed.
