### ISSUE TITLE
After my 1st unit destroys an enemy unit the game switches to 2nd unit

### ISSUE THREAD

**Issue by kazgaroth011** [SWY1985/CivOne#323]
even though my 1st unit still has some turns left.

**Comment by SWY1985** [comment]
Linked to #280 
I've tried finding out what causes this but it's very hard to pin point.

**Comment by AlexFolland** [comment]
This is the same bug as https://github.com/SWY1985/CivOne/issues/300, which was closed but I can't find the commit that fixed it.

**Comment by SWY1985** [comment]
Issue #300 got closed because I thought it was solved. The unit doesn't lose the rest of their turns, it just loses focus, like the Wait order was given directly after attacking.
This issue has my main focus as it's the most annoying bug there is at the moment. Hopefully I can solve it soon.

**Comment by AlexFolland** [comment]
Oh.  When I reported it, the unit had actually lost all the rest of its turns after destroying an enemy unit on its first movement.

**Comment by AlexFolland** [comment]
Also, sorry, I still have yet to go and play another game of CivOne for testing these things.  I've been distracted with playing another fun/silly game, but I am still excited to get back to testing CivOne more.

**Comment by AlexFolland** [comment]
This might have been fixed when https://github.com/SWY1985/CivOne/issues/300 was fixed.  @kazgaroth011, can you confirm?  The problem was that attacking was removing movement points based on the enemy unit's tile's terrain type.

**Comment by SWY1985** [comment]
This issue is not resolved, and I still have no idea what causes it. To be continued...

**Comment by SWY1985** [comment]
I have figured out why this happens, solution on the way...
